name: Stockpyt Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - release/*

jobs:
  build:
    runs-on: python/3.8-buster
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup python unit tests
        run: |
          python -m pip install --upgrade pip
          pip install -e .[ci]
      - name: Run unit tests
        run: pytest tests
